## Classifier

In [1]:
from sklearn.datasets import load_iris

In [6]:
X  , y = load_iris(return_X_y=True)

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size=0.33 ,random_state=42)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
knn_clf=KNeighborsClassifier()

In [13]:
knn_clf.fit(X_train  , y_train)

KNeighborsClassifier()

In [14]:
y_pred=knn_clf.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report , precision_score , recall_score

In [20]:
print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))
print(precision_score(y_test , y_pred , average='weighted'))
print(recall_score(y_test , y_pred , average='weighted'))

0.98
[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50

0.98125
0.98


In [21]:
from sklearn.model_selection import GridSearchCV

In [28]:
param_grid={

    'n_neighbors' : [1,2,3,4,5,6,7,8,9],
    'algorithm' : ['auto' , 'ball_tree' , 'kd_tree' , 'brute'],
    'p' :[1,2]
}

In [29]:
knn_clf1=KNeighborsClassifier()

In [30]:
gscv=GridSearchCV(knn_clf1 , param_grid=param_grid , refit=True , cv=3 , verbose=2)

In [31]:
gscv.fit(X_train , y_train)

Fitting 3 folds for each of 72 candidates, totalling 216 fits
[CV] END .................algorithm=auto, n_neighbors=1, p=1; total time=   0.0s
[CV] END .................algorithm=auto, n_neighbors=1, p=1; total time=   0.0s
[CV] END .................algorithm=auto, n_neighbors=1, p=1; total time=   0.0s
[CV] END .................algorithm=auto, n_neighbors=1, p=2; total time=   0.0s
[CV] END .................algorithm=auto, n_neighbors=1, p=2; total time=   0.0s
[CV] END .................algorithm=auto, n_neighbors=1, p=2; total time=   0.0s
[CV] END .................algorithm=auto, n_neighbors=2, p=1; total time=   0.0s
[CV] END .................algorithm=auto, n_neighbors=2, p=1; total time=   0.0s
[CV] END .................algorithm=auto, n_neighbors=2, p=1; total time=   0.0s
[CV] END .................algorithm=auto, n_neighbors=2, p=2; total time=   0.0s
[CV] END .................algorithm=auto, n_neighbors=2, p=2; total time=   0.0s
[CV] END .................algorithm=auto, n_nei

GridSearchCV(cv=3, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9],
                         'p': [1, 2]},
             verbose=2)

In [33]:
gscv.best_params_

{'algorithm': 'auto', 'n_neighbors': 1, 'p': 2}

In [34]:
gscv.best_score_

0.9497920380273323

In [36]:
clf=KNeighborsClassifier(algorithm='auto' , n_neighbors=1 , p=2 )

In [37]:
clf.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=1)

In [39]:
y_pred=clf.predict(X_test)

In [40]:
print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))
print(precision_score(y_test , y_pred , average='weighted'))
print(recall_score(y_test , y_pred , average='weighted'))

0.98
[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50

0.98125
0.98


In [41]:
wt_voting_knn=KNeighborsClassifier(weights='distance' , algorithm='auto' , n_neighbors=1 , p=2)

In [42]:
wt_voting_knn.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=1, weights='distance')

In [43]:
y_pred=wt_voting_knn.predict(X_test)

In [44]:
print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))
print(precision_score(y_test , y_pred , average='weighted'))
print(recall_score(y_test , y_pred , average='weighted'))

0.98
[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50

0.98125
0.98


In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
std=StandardScaler()

In [48]:
X_train_scaled=std.fit_transform(X_train)
X_test_scaled=std.transform(X_test)

In [49]:
knn_clf2=KNeighborsClassifier(weights='distance' , algorithm='auto' , n_neighbors=1 , p=2)

In [51]:
knn_clf2.fit(X_train_scaled , y_train)

KNeighborsClassifier(n_neighbors=1, weights='distance')

In [52]:
y_pred=knn_clf2.predict(X_test_scaled)

In [53]:
print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))
print(precision_score(y_test , y_pred , average='weighted'))
print(recall_score(y_test , y_pred , average='weighted'))

0.96
[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50

0.96
0.96


In [54]:
import numpy as np

In [56]:
np.square(8-4)

16

In [59]:
def euclidean_distance(x1 , y1 , x2 , y2):
    x=np.square(x1-x2)
    y=np.square(y1-y2)
    z=x+y
    return round(np.sqrt(z) , 2)

In [60]:
print(euclidean_distance(5 , 4 , 7 , 8))

4.47


In [61]:
def manhattan_dist(x1 , y1 , x2 , y2):
    x=np.abs(x1-x2)
    y=np.abs(y1-y2)
    z=x+y
    return z

In [63]:
print(manhattan_dist(5 , 4 , 7 , 8))

6


## Regression

In [89]:
import pandas as pd

<ipython-input-89-7dd3504c366f>:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [90]:
df=pd.read_csv("Boston.csv")

In [91]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

   LSTAT  MEDV  
0   4.98  24.0  
1   9.14  21.6  
2   4.03  34.7  
3   2.94  33.4  
4   5.33  36.2

In [92]:
X=df.iloc[: , :-1]
y=df.iloc[: , -1]

In [94]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.33 ,random_state=42)

In [95]:
from sklearn.neighbors import KNeighborsRegressor

In [96]:
knn_reg1=KNeighborsRegressor()

In [97]:
knn_reg1.fit(X_train , y_train)

KNeighborsRegressor()

In [98]:
y_pred=knn_reg1.predict(X_test)

In [99]:
from sklearn.metrics import r2_score , mean_absolute_error, mean_squared_error

In [100]:
print(r2_score(y_test , y_pred))
print(mean_absolute_error(y_test , y_pred))
print(mean_squared_error(y_test , y_pred))

0.6144019529783294
3.6804790419161675
29.181485029940124


In [101]:
knn_reg2=KNeighborsRegressor(weights='distance')

In [102]:
knn_reg2.fit(X_train , y_train)

KNeighborsRegressor(weights='distance')

In [103]:
y_pred=knn_reg2.predict(X_test)

In [104]:
print(r2_score(y_test , y_pred))
print(mean_absolute_error(y_test , y_pred))
print(mean_squared_error(y_test , y_pred))

0.6282032382442895
3.546776246572624
28.13702434738923


In [105]:
param_grid={
    'n_neighbors' : [1,2,3,4,5,6,7,8,9],
    'algorithm' : ['auto' , 'ball_tree' , 'kd_tree' , 'brute'],
    'p' :[1,2] ,
    'weights' : ['uniform' , 'distance']
}

In [106]:
gscv=GridSearchCV(KNeighborsRegressor() , param_grid=param_grid , cv=3 , refit=True , verbose=2)

In [107]:
gscv.fit(X_train , y_train)

Fitting 3 folds for each of 144 candidates, totalling 432 fits
[CV] END algorithm=auto, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=auto, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=auto, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=auto, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=auto, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=auto, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=auto, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=auto, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=auto, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=auto, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=auto, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=auto, n_neighbors=1, p

GridSearchCV(cv=3, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9],
                         'p': [1, 2], 'weights': ['uniform', 'distance']},
             verbose=2)

In [108]:
gscv.best_params_

{'algorithm': 'auto', 'n_neighbors': 6, 'p': 1, 'weights': 'distance'}

In [109]:
gscv.best_score_

0.6370614814441895

In [111]:
knn_reg3=KNeighborsRegressor(algorithm='auto' , n_neighbors=6 ,p=1 , weights='distance')

In [112]:
knn_reg3.fit(X_train , y_train)

KNeighborsRegressor(n_neighbors=6, p=1, weights='distance')

In [114]:
y_pred=knn_reg3.predict(X_test)

In [115]:
print(r2_score(y_test , y_pred))
print(mean_absolute_error(y_test , y_pred))
print(mean_squared_error(y_test , y_pred))

0.6562254940139136
3.2171791039643347
26.01634182951205


In [116]:
std=StandardScaler()

In [118]:
X_train_scaled=std.fit_transform(X_train)
X_test_scaled=std.transform(X_test)

In [119]:
knn_reg4=KNeighborsRegressor(algorithm='auto' , n_neighbors=6 ,p=1 , weights='distance')

In [120]:
knn_reg4.fit(X_train_scaled , y_train)

KNeighborsRegressor(n_neighbors=6, p=1, weights='distance')

In [121]:
y_pred=knn_reg4.predict(X_test_scaled)

In [122]:
print(r2_score(y_test , y_pred))
print(mean_absolute_error(y_test , y_pred))
print(mean_squared_error(y_test , y_pred))

0.7593773873193542
2.620121440170009
18.209960408359446
