In [72]:
import pandas as pd
import numpy as np

df=pd.read_csv("tips.csv")

df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

### What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its application

Min-Max scaling, also known as normalization, is a data preprocessing technique used to scale the features of your data to a fixed range, typically [0, 1]. This is particularly useful when you want to ensure that all features contribute equally to the model, especially when they have different units or scales.

**Why Use Min-Max Scaling?**
Uniform Contribution: Ensures that all features contribute equally to the model.
Algorithm Sensitivity: Some algorithms, like K-Nearest Neighbors (KNN) and Neural Networks, are sensitive to the scale of the data.
Preserves Relationships: Maintains the relationships between the data points.

In [73]:
## Eg : 

from sklearn.preprocessing import MinMaxScaler
min_max_scaler=MinMaxScaler()
min_max_scaler.fit_transform(df[['total_bill' , 'tip']])

min_max_scaler.transform([[23, 9]])


/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.41746963, 0.88888889]])

### What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling? Provide an example to illustrate its application


The Unit Vector technique, also known as normalization, scales each data point (row) to have a unit norm (length of 1). This is different from Min-Max scaling, which scales features to a fixed range, typically [0, 1].

**Unit Vector Scaling (Normalization):**

Function: Scales each data point to have a unit norm.
Use Case: Useful when you want to ensure that each data point has the same length, often used in clustering algorithms like K-Means and in text classification.

In [74]:

from sklearn.preprocessing import Normalizer

unit_vector=Normalizer()
unit_vector.fit_transform(df[['total_bill']])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

### What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an  example to illustrate its application


**Principal Component Analysis (PCA)** is a statistical technique used for dimensionality reduction. It transforms the data into a new coordinate system where the greatest variances by any projection of the data come to lie on the first coordinates (called principal components), the second greatest variances on the second coordinates, and so on.


**Why Use PCA?**
Dimensionality Reduction: Reduces the number of features while retaining the most important information.
Visualization: Helps in visualizing high-dimensional data in 2D or 3D.
Noise Reduction: Removes noise and redundancy in the data.
Improves Performance: Can improve the performance of machine learning algorithms by reducing overfitting.

**Principal Components are New Axes:**

Principal components are new directions in the feature space. They are not the same as the original features but are derived from them.
Each principal component is a linear combination of the original features.

**Maximizing Variance:**

The first principal component (PC1) is the direction that captures the maximum variance in the data. It is the direction along which the data points are most spread out.
The second principal component (PC2) is orthogonal to PC1 and captures the next highest variance.

### What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature Extraction? Provide an example to illustrate this concept

**Relationship Between PCA and Feature Extraction**
Principal Component Analysis (PCA) is a powerful technique used for feature extraction. Feature extraction involves creating new features from the existing ones, and PCA does this by transforming the original features into a new set of features called principal components. These principal components capture the most important information (variance) in the data, effectively reducing its dimensionality.

**How PCA is Used for Feature Extraction**

1. Identify Principal Components: PCA identifies the directions (principal components) in which the data varies the most.
2. Transform Data: The original data is transformed into a new coordinate system defined by these principal components.
3. Reduce Dimensionality: By selecting the top principal components, you can reduce the number of features while retaining the most important information

### You are working on a project to build a recommendation system for a food delivery service. The dataset  contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to  preprocess the data.

In [76]:

features=['price' , 'rating' , 'delivery time' ]

price=np.random.randint(1 , 500 , 100)
rating =np.random.uniform(1 , 5 ,100)
rating=np.round(rating , 1)
time=np.random.randint(25 ,40 , 100)


In [79]:
df1=pd.DataFrame(price , columns=['Price'])
df2=pd.DataFrame(rating ,  columns=['rating'])
df3=pd.DataFrame(time , columns=['delivery time'])

In [81]:
final_df=pd.concat((df1 , df2 , df3) , axis=1)
final_df

Price  rating  delivery time
0     143     4.3             36
1     296     4.0             30
2     479     2.0             34
3     378     3.7             29
4     234     1.4             33
..    ...     ...            ...
95    195     3.5             31
96    453     1.7             31
97    416     2.4             28
98    489     4.1             25
99    322     1.5             28

[100 rows x 3 columns]

In [83]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaler.fit_transform(final_df[['Price' , 'rating' , 'delivery time']])

array([[0.26899384, 0.825     , 0.78571429],
       [0.58316222, 0.75      , 0.35714286],
       [0.95893224, 0.25      , 0.64285714],
       [0.75154004, 0.675     , 0.28571429],
       [0.45585216, 0.1       , 0.57142857],
       [0.34907598, 0.775     , 0.92857143],
       [0.29568789, 0.85      , 0.85714286],
       [0.22587269, 0.75      , 0.        ],
       [0.77207392, 0.8       , 0.71428571],
       [0.74332649, 0.125     , 0.85714286],
       [0.63039014, 0.2       , 0.07142857],
       [0.56673511, 0.1       , 0.42857143],
       [0.28336756, 0.925     , 0.07142857],
       [0.93839836, 0.95      , 0.21428571],
       [0.54620123, 0.375     , 1.        ],
       [0.30184805, 0.9       , 0.42857143],
       [0.26488706, 0.85      , 0.21428571],
       [0.33470226, 0.875     , 0.78571429],
       [0.91991786, 0.15      , 0.85714286],
       [0.60574949, 0.25      , 0.21428571],
       [0.98767967, 0.05      , 0.57142857],
       [0.83778234, 0.075     , 0.42857143],
       [0.

In [84]:
scaler.transform([[200 , 4.5 , 30]])

/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.38603696, 0.875     , 0.35714286]])

### You are working on a project to build a model to predict stock prices. The dataset contains many  features, such as company financial data and market trends. Explain how you would use PCA to reduce the  dimensionality of the dataset



Using Principal Component Analysis (PCA) to reduce the dimensionality of a dataset for predicting stock prices is a great approach. Here's how you can do it step-by-step:

#### **Step-by-Step Process**

**Standardize the Data:**
Before applying PCA, it's important to standardize the data so that each feature has a mean of 0 and a standard deviation of 1. This ensures that each feature contributes equally to the analysis.

**Apply PCA:**
Use PCA to transform the standardized data into a new set of features (principal components) that capture the most variance in the data.

**Select the Number of Principal Components:**
Choose the number of principal components that explain a significant amount of the variance in the data. This can be done by examining the explained variance ratio.

**Transform the Data:**
Transform the original data into the reduced set of principal components.


### For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the values to a range of -1 to 1

In [87]:
data=np.array([1,5,10,15,20]).reshape(-1,1)

In [88]:
data

array([[ 1],
       [ 5],
       [10],
       [15],
       [20]])

In [90]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler(feature_range=(-1,1))
scaled_data=scaler.fit_transform(data)

In [91]:
scaled_data

array([[-1.        ],
       [-0.57894737],
       [-0.05263158],
       [ 0.47368421],
       [ 1.        ]])

In [92]:
scaled_data.flatten()

array([-1.        , -0.57894737, -0.05263158,  0.47368421,  1.        ])

### For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform Feature Extraction using PCA. How many principal components would you choose to retain, and why?

In [97]:
data = {
    'height': [170, 160, 180, 175, 165],
    'weight': [70, 60, 80, 75, 65],
    'age': [25, 30, 35, 40, 45],
    'gender': ['male', 'female', 'male', 'female', 'male'],
    'blood_pressure': [120, 110, 130, 125, 115]
}


In [98]:
data=pd.DataFrame(data)

In [99]:
data

height  weight  age  gender  blood_pressure
0     170      70   25    male             120
1     160      60   30  female             110
2     180      80   35    male             130
3     175      75   40  female             125
4     165      65   45    male             115

In [100]:
def encode_gender(gender):
    if gender=="male":
        return 1
    else:
        return 0

In [103]:
data['gender']=data['gender'].apply(encode_gender)

In [104]:
data

height  weight  age  gender  blood_pressure
0     170      70   25       1             120
1     160      60   30       0             110
2     180      80   35       1             130
3     175      75   40       0             125
4     165      65   45       1             115

In [106]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit_transform(data[['height' , 'weight' , 'age' , 'blood_pressure']])

array([[ 0.        ,  0.        , -1.41421356,  0.        ],
       [-1.41421356, -1.41421356, -0.70710678, -1.41421356],
       [ 1.41421356,  1.41421356,  0.        ,  1.41421356],
       [ 0.70710678,  0.70710678,  0.70710678,  0.70710678],
       [-0.70710678, -0.70710678,  1.41421356, -0.70710678]])

In [108]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline(steps=[
    ('pca', pca)
])

pipeline.fit(data)

Pipeline(steps=[('pca', PCA(n_components=2))])

In [111]:
explained_variance = pca.explained_variance_ratio_
print(explained_variance)
print(len(explained_variance))

[0.75291771 0.24598477]
2


In [110]:
cumulative_variance = explained_variance.cumsum()
cumulative_variance

array([0.75291771, 0.99890248])