In [33]:
import numpy as np

In [1]:
!pip install Xgboost


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# Classification

In [2]:
from sklearn.datasets import make_classification
X , y = make_classification(n_samples=1000 , n_features=4 , n_classes=2 , n_redundant=0 , n_informative=2 , shuffle=False)

In [5]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X  ,y , test_size=0.33 , random_state=42)

In [6]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xg

## Adaboost 

In [8]:
clf1=AdaBoostClassifier()
clf1.fit(X_train , y_train)

AdaBoostClassifier()

In [9]:
y_pred=clf1.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report , precision_score , recall_score

In [15]:
print(f"clf1 accuracy : {accuracy_score(y_test , y_pred)}")
print(f"clf1 confusion matrix\n {confusion_matrix(y_test , y_pred)}")
print(f"clf1 classfication report {classification_report(y_test , y_pred)}")
print(f"clf1 precision {precision_score(y_test , y_pred)}")
print(f"clf1 recall {recall_score(y_test , y_pred)}")

clf1 accuracy : 0.9757575757575757
clf1 confusion matrix
 [[157   6]
 [  2 165]]
clf1 classfication report               precision    recall  f1-score   support

           0       0.99      0.96      0.98       163
           1       0.96      0.99      0.98       167

    accuracy                           0.98       330
   macro avg       0.98      0.98      0.98       330
weighted avg       0.98      0.98      0.98       330

clf1 precision 0.9649122807017544
clf1 recall 0.9880239520958084


## Gradient Boosting 

In [16]:
clf2=GradientBoostingClassifier()
clf2.fit(X_train, y_train)

GradientBoostingClassifier()

In [18]:
y_pred=clf2.predict(X_test)

In [19]:
print(f"clf2 accuracy : {accuracy_score(y_test , y_pred)}")
print(f"clf2 confusion matrix\n {confusion_matrix(y_test , y_pred)}")
print(f"clf2 classfication report {classification_report(y_test , y_pred)}")
print(f"clf2 precision {precision_score(y_test , y_pred)}")
print(f"clf2 recall {recall_score(y_test , y_pred)}")

clf2 accuracy : 0.9787878787878788
clf2 confusion matrix
 [[158   5]
 [  2 165]]
clf2 classfication report               precision    recall  f1-score   support

           0       0.99      0.97      0.98       163
           1       0.97      0.99      0.98       167

    accuracy                           0.98       330
   macro avg       0.98      0.98      0.98       330
weighted avg       0.98      0.98      0.98       330

clf2 precision 0.9705882352941176
clf2 recall 0.9880239520958084


## XGBoost

In [21]:
clf3=xg.XGBClassifier()
clf3.fit(X_train , y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [22]:
y_pred=clf3.predict(X_test)

In [23]:
print(f"clf3 accuracy : {accuracy_score(y_test , y_pred)}")
print(f"clf3 confusion matrix\n {confusion_matrix(y_test , y_pred)}")
print(f"clf3 classfication report {classification_report(y_test , y_pred)}")
print(f"clf3 precision {precision_score(y_test , y_pred)}")
print(f"clf3 recall {recall_score(y_test , y_pred)}")

clf3 accuracy : 0.9818181818181818
clf3 confusion matrix
 [[159   4]
 [  2 165]]
clf3 classfication report               precision    recall  f1-score   support

           0       0.99      0.98      0.98       163
           1       0.98      0.99      0.98       167

    accuracy                           0.98       330
   macro avg       0.98      0.98      0.98       330
weighted avg       0.98      0.98      0.98       330

clf3 precision 0.9763313609467456
clf3 recall 0.9880239520958084


**Gardient and XGBoost performs very well**

# Regression

In [24]:
from sklearn.datasets import make_regression
X , y = make_regression(n_samples=1000 , n_features=4 , n_informative=2 , shuffle=False)

In [26]:
X_train ,X_test , y_train , y_test = train_test_split(X , y , test_size=0.33 , random_state=42)

## Adaboost Regressor

In [27]:
from sklearn.ensemble import AdaBoostRegressor

In [28]:
reg1=AdaBoostRegressor()
reg1.fit(X_train , y_train)

AdaBoostRegressor()

In [29]:
y_pred=reg1.predict(X_test)

In [30]:
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score

In [34]:
print(f"reg1 r2_score/accuracy = {r2_score(y_test , y_pred)}")
print(f"Mean Absolute error = {mean_absolute_error(y_test , y_pred)}")
print(f"Mean Squared error = {mean_squared_error(y_test , y_pred)}")
print(f"Root Mean Squared error = {np.sqrt(mean_squared_error(y_test , y_pred))}")

reg1 r2_score/accuracy = 0.9540351934306874
Mean Absolute error = 9.563514803940436
Mean Squared error = 168.0418824359199
Root Mean Squared error = 12.963096946174549


## Gradient Boost Regressor

In [35]:
from sklearn.ensemble import GradientBoostingRegressor

In [36]:
reg2=GradientBoostingRegressor()

In [37]:
reg2.fit(X_train , y_train)

GradientBoostingRegressor()

In [38]:
y_pred=reg2.predict(X_test)

In [39]:
print(f"reg2 r2_score/accuracy = {r2_score(y_test , y_pred)}")
print(f"Mean Absolute error = {mean_absolute_error(y_test , y_pred)}")
print(f"Mean Squared error = {mean_squared_error(y_test , y_pred)}")
print(f"Root Mean Squared error = {np.sqrt(mean_squared_error(y_test , y_pred))}")

reg2 r2_score/accuracy = 0.9954293093239752
Mean Absolute error = 2.9357949688145606
Mean Squared error = 16.709903131503356
Root Mean Squared error = 4.0877748386504065


## XGBoost Regressor

In [40]:
reg3 = xg.XGBRegressor()

In [41]:
reg3.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [42]:
y_pred=reg3.predict(X_test)

In [43]:
print(f"reg3 r2_score/accuracy = {r2_score(y_test , y_pred)}")
print(f"Mean Absolute error = {mean_absolute_error(y_test , y_pred)}")
print(f"Mean Squared error = {mean_squared_error(y_test , y_pred)}")
print(f"Root Mean Squared error = {np.sqrt(mean_squared_error(y_test , y_pred))}")

reg3 r2_score/accuracy = 0.9948905451007736
Mean Absolute error = 2.6933199979062667
Mean Squared error = 18.679561246335485
Root Mean Squared error = 4.321985798951158
