In [2]:
import pandas as pd
import numpy as np

<ipython-input-2-baf368f80de7>:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df=pd.DataFrame({
    'color' : ['red' , 'green' , 'blue' , 'green' , 'red' , 'blue']
})

In [6]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder()
encoded=ohe.fit_transform(df[['color']]).toarray()

In [7]:
encoded

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [12]:
encoded_df=pd.DataFrame(data=encoded , columns=ohe.get_feature_names_out())
final_df=pd.concat([df , encoded_df] , axis=1)
final_df

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1  green         0.0          1.0        0.0
2   blue         1.0          0.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

### Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you  might choose one over the other

**Ordinal Encoding**

Definition: Ordinal encoding assigns a unique integer to each category, preserving the order of the categories.
Use Case: When the categorical data has a meaningful order or ranking.
Example: For a feature like "Education Level" with categories ["High School", "Bachelor's", "Master's", "PhD"], ordinal encoding might assign:
High School: 0
Bachelor's: 1
Master's: 2
PhD: 3

**Label Encoding**
Definition: Label encoding assigns a unique integer to each category without considering any order.
Use Case: When the categorical data does not have an inherent order.
Example: For a feature like "Color" with categories ["Red", "Green", "Blue"], label encoding might assign:
Red: 0
Green: 1
Blue: 2



In [13]:
df=pd.DataFrame({
    'degree' : ["High School", "Bachelor's", "Master's", "PhD"]
})

In [14]:
df

degree
0  High School
1   Bachelor's
2     Master's
3          PhD

In [15]:
from sklearn.preprocessing import OrdinalEncoder

encoder=OrdinalEncoder(categories=[["High School" , "Bachelor's" , "Master's" ,  "PhD"]])

In [18]:
encoded_data=encoder.fit_transform(df[['degree']])

In [21]:
encoded_data=encoded_data.flatten()
encoded_data

array([0., 1., 2., 3.])

In [22]:
encoded_df=pd.DataFrame(encoded_data , columns=['encoded_data'])

In [25]:
final_df=pd.concat([df  , encoded_df] , axis=1)
final_df

degree  encoded_data
0  High School           0.0
1   Bachelor's           1.0
2     Master's           2.0
3          PhD           3.0

In [26]:
df=pd.DataFrame({
    'color' : ['red' , 'green' , 'blue' , 'green' , 'red' , 'blue']
})

In [27]:
df

color
0    red
1  green
2   blue
3  green
4    red
5   blue

In [31]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()
encoded_data=encoder.fit_transform(df[['color']])
encoded_data

/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 0, 1, 2, 0])

In [33]:
encoded_df=pd.DataFrame(encoded_data , columns=['encoded_data'])
final_df=pd.concat([df ,encoded_df] , axis=1)
final_df

color  encoded_data
0    red             2
1  green             1
2   blue             0
3  green             1
4    red             2
5   blue             0

### Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in a machine learning project.

In [34]:
data = [
    {"City": "New York", "Price": 100},
    {"City": "Los Angeles", "Price": 150},
    {"City": "Chicago", "Price": 120},
    {"City": "Houston", "Price": 130},
    {"City": "Phoenix", "Price": 110}
]

In [36]:
df=pd.DataFrame(data)

In [37]:
df

City  Price
0     New York    100
1  Los Angeles    150
2      Chicago    120
3      Houston    130
4      Phoenix    110

In [40]:
encoded_data=df.groupby(by="City")['Price'].mean().to_dict()
encoded_data

{'Chicago': 120.0,
 'Houston': 130.0,
 'Los Angeles': 150.0,
 'New York': 100.0,
 'Phoenix': 110.0}

In [42]:
df['Encoded_city']=df['City'].map(encoded_data)
df

City  Price  Encoded_city
0     New York    100         100.0
1  Los Angeles    150         150.0
2      Chicago    120         120.0
3      Houston    130         130.0
4      Phoenix    110         110.0

### Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated



Covariance it explain the realtionship between two random variable . If the ovariance is positive then the features (x , y) are directly proportional i.e if x goes up y also goes up and vice versa . If the covariance is negative the features are indirectly proportional that is if x goes up y goes down and vice versa

Formula : sum i=1 to n  (xi-x_mean)(yi-y_mean)/n

Disadvantages : The result of the covarinace is number with no specifc range which eventually dont specify the strength of associataion.To solve this issue correlation is needed.

In [46]:
data = [
    {"City": "New York", 'GDP': 3.5 ,  "Price": 100},
    {"City": "Los Angeles", 'GDP': 7.4 , "Price": 150},
    {"City": "Chicago", 'GDP': 4.0 , "Price": 120},
    {"City": "Houston", 'GDP': 9.0 ,  "Price": 130},
    {"City": "Phoenix", 'GDP': 8.9 , "Price": 110}
]

df=pd.DataFrame(data)

In [49]:
df[['GDP' , 'Price']].cov()

GDP   Price
GDP     7.013   21.85
Price  21.850  370.00

### Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,  large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library. Show your code and explain the output

In [1]:
data = {
    'Color': ['red', 'green', 'blue'],
    'Size': ['small', 'medium', 'large'],
    'Material': ['wood', 'metal', 'plastic']
}

In [3]:
df=pd.DataFrame(data)

In [4]:
df

Color    Size Material
0    red   small     wood
1  green  medium    metal
2   blue   large  plastic

In [10]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()

df['Color_Encoded']=encoder.fit_transform(df[['Color']])
df['Size_Encoded']=encoder.fit_transform(df[['Size']])
df['Material_Encoded']=encoder.fit_transform(df[['Material']])

/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
df

Color    Size Material  Color_Encoded  Size_Encoded  Material_Encoded
0    red   small     wood              2             2                 2
1  green  medium    metal              1             1                 0
2   blue   large  plastic              0             0                 1

### Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education level. Interpret the results

In [12]:
data = {
    'Age': [25, 32, 47, 51, 62],
    'Income': [50000, 60000, 80000, 95000, 110000],
    'Education_level': [12, 14, 16, 18, 20]
}

In [13]:
df=pd.DataFrame(data)

In [14]:
df

Age  Income  Education_level
0   25   50000               12
1   32   60000               14
2   47   80000               16
3   51   95000               18
4   62  110000               20

In [15]:
df.cov()

Age       Income  Education_level
Age                 221.3     363000.0             46.5
Income           363000.0  605000000.0          77500.0
Education_level      46.5      77500.0             10.0

### Q6. You are working on a machine learning project with a dataset containing several categorical variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD), and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for each variable, and why?

In [16]:
data = {
    'Gender': ['Male', 'Female', 'Female', 'Male'],
    'Education Level': ['High School', 'Bachelor\'s', 'Master\'s', 'PhD'],
    'Employment Status': ['Unemployed', 'Part-Time', 'Full-Time', 'Unemployed']
}

In [17]:
df=pd.DataFrame(data)

In [18]:
df

Gender Education Level Employment Status
0    Male     High School        Unemployed
1  Female      Bachelor's         Part-Time
2  Female        Master's         Full-Time
3    Male             PhD        Unemployed

In [27]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [20]:
label_encoder=LabelEncoder()
df['Encoded_Gender']=label_encoder.fit_transform(df[['Gender']])

/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [26]:
education_encoder = OrdinalEncoder(categories=[['High School', 'Bachelor\'s', 'Master\'s', 'PhD']])
df['Education_encoded'] = education_encoder.fit_transform(df[['Education Level']])

In [31]:
onehot_encoder=OneHotEncoder()
encoded_ohe=onehot_encoder.fit_transform(df[['Employment Status']]).toarray()
encoded_ohe

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [ ]:
pd.DataFrame(encoded_ohe , columns=onehot_encoder.)