In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.datasets import load_iris

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
data=load_iris()

In [8]:
type(data)

sklearn.utils._bunch.Bunch

In [9]:
X , y = load_iris(return_X_y=True)

In [12]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.3 , random_state=42)

In [14]:
print(X_train.shape , y_train.shape)
print(X_test.shape , y_test.shape)

(105, 4) (105,)
(45, 4) (45,)


In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
gnb=GaussianNB()
gnb.fit(X_train  , y_train)

GaussianNB()

In [18]:
y_pred=gnb.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix , classification_report , accuracy_score

In [21]:
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))
print(accuracy_score(y_test , y_pred))

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

0.9777777777777777


In [23]:
from sklearn.metrics import precision_score , recall_score
print(precision_score(y_test , y_pred , average='weighted'))
print(recall_score(y_test , y_pred , average='weighted'))

0.9793650793650793
0.9777777777777777


In [58]:
df=sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [59]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()
df['sex']=encoder.fit_transform(df['sex'])

In [60]:
df['smoker']=encoder.fit_transform(df['smoker'])

In [61]:
df.head()

total_bill   tip  sex  smoker  day    time  size
0       16.99  1.01    0       0  Sun  Dinner     2
1       10.34  1.66    1       0  Sun  Dinner     3
2       21.01  3.50    1       0  Sun  Dinner     3
3       23.68  3.31    1       0  Sun  Dinner     2
4       24.59  3.61    0       0  Sun  Dinner     4

In [62]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [63]:
from sklearn.preprocessing import OrdinalEncoder

categories=[['Thur', 'Sun' , 'Fri' , 'Sat' ]]

In [64]:
ordinal=OrdinalEncoder(categories=categories)
encoded=ordinal.fit_transform(df[['day']])
encoded=encoded.flatten()

df['day']=encoded

In [65]:
df['day']=df['day'].astype('int')

In [66]:
df.head()

total_bill   tip  sex  smoker  day    time  size
0       16.99  1.01    0       0    1  Dinner     2
1       10.34  1.66    1       0    1  Dinner     3
2       21.01  3.50    1       0    1  Dinner     3
3       23.68  3.31    1       0    1  Dinner     2
4       24.59  3.61    0       0    1  Dinner     4

In [67]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [68]:
categories=[['Lunch' , 'Dinner']]

In [69]:
ordi=OrdinalEncoder(categories=categories)

In [70]:
encoded=ordi.fit_transform(df[['time']])
encoded=encoded.flatten()
encoded

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0.

In [71]:
df['time']=encoded

In [72]:
df['time']=df['time'].astype('int')

In [73]:
df.head()

total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    1     1     2
1       10.34  1.66    1       0    1     1     3
2       21.01  3.50    1       0    1     1     3
3       23.68  3.31    1       0    1     1     2
4       24.59  3.61    0       0    1     1     4

In [75]:
X=df.iloc[: , :-2]

In [77]:
x1=df.iloc[: , -1]

In [80]:
X=pd.concat([X  ,x1] , axis=1)
y=df.iloc[: , -2]

In [82]:
from sklearn.model_selection import train_test_split

X_train, X_test , y_train , y_test=train_test_split(X , y , test_size=0.3 , random_state=42)

In [83]:
from sklearn.naive_bayes import GaussianNB

gsb=GaussianNB()
gsb.fit(X_train , y_train)
y_pred=gsb.predict(X_test)

In [84]:
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))
print(accuracy_score(y_test , y_pred))

[[16  3]
 [ 4 51]]
              precision    recall  f1-score   support

           0       0.80      0.84      0.82        19
           1       0.94      0.93      0.94        55

    accuracy                           0.91        74
   macro avg       0.87      0.88      0.88        74
weighted avg       0.91      0.91      0.91        74

0.9054054054054054


In [85]:
from sklearn.metrics import precision_score , recall_score
print(precision_score(y_test , y_pred , average='weighted'))
print(recall_score(y_test , y_pred , average='weighted'))

0.9073573573573573
0.9054054054054054


In [86]:
gsb.class_count_

array([ 49., 121.])

In [87]:
gsb.class_prior_

array([0.28823529, 0.71176471])

In [89]:
gsb.classes_

array([0, 1])

In [90]:
gsb.epsilon_

8.204731953287197e-08